---
title: "Brreg html table"
author: "Ørjan Myrland"
date: "08.10.2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Måte 1 og gjøre det på
```{r}
# rydder environment og laster pakker 
rm(list = ls())
library(rvest)
library(tidyverse)
library(rlist)
library(splitstackshape)


# henter ned nettside 
page <- read_html("https://w2.brreg.no/kunngjoring/kombisok.jsp?datoFra=07.10.2017&datoTil=07.10.2018&id_region=100&id_fylke=19&id_kommune=-+-+-&id_niva1=51&id_niva2=-+-+-&id_bransje1=0")

# Tabbelen vi er ute etter er table 4 fra nettsiden 
brreg <- html_table(html_nodes(page, "table")[[4]], fill = TRUE)

# ser på lengden av rader
num_rows <- nrow(brreg)

# Fjerner unødvendige kolloner og rader 
brreg <- brreg[2:8]  
brreg <- slice(brreg, 8:num_rows) 
brreg <- brreg[-2] 
brreg <- brreg[-3] 
brreg <- brreg[-4]
brreg <- brreg[-349,]


# gir variablene nye navn 
colnames(brreg)[1:4] <- c("Navn","orgnr", "dato", "kunngjøringstype") 

# ser på det ferdige datasettet
head(brreg)


#Removing blankspace and converting type for company_num
brreg$orgnr <- str_replace_all(string= brreg$orgnr, pattern=" ", repl="")
brreg$orgnr <- as.numeric(brreg$orgnr)

#Converting type for date
brreg$dato <- as.Date(brreg$dato, "%d.%m.%Y")

head(brreg)

# Fjerner privatpersoner og filtrerer for bare tvangsavvikling 
brregfirma <- brreg %>%
  filter( nchar(orgnr) > 6) %>%
  filter(kunngjøringstype == "Tvangsavvikling")

# Tvangsavviklinger i Troms siste år. 
print(brregfirma)

# Tabellen for bare privatpersoner:
brregprivat <- brreg %>%
  filter( nchar(orgnr) < 9)


# plot over utviklingen siste år 
ggplot() +
  geom_bar(data = brreg, aes ( kunngjøringstype), colour="#FF0000", fill="#FF1000") +
  labs(
        title = "Konkurs / tvangsavvikling 07.10.17 - 07.10.18 Troms",
        x = "Kunngjøringstype",
        y = "Nummer") 

```

Alternativ måte
```{r}
rm(list=ls())

library(rvest)
library(rlist)
library(tidyverse)


page1 <- read_html("https://w2.brreg.no/kunngjoring/kombisok.jsp?datoFra=07.10.2017&datoTil=07.10.2018&id_region=100&id_fylke=19&id_kommune=-+-+-&id_niva1=51&id_niva2=-+-+-&id_bransje1=0")

page1%>% html_nodes("tr")

brreg1 <- page1%>% html_nodes("tr") %>% html_text()
brreg1 <- tibble(brreg1)
head(brreg1)

brreg1 <- brreg1[-c(1:16,349,350,351), ]

head(brreg1)

```

