---
title: "Stock prices"
author: "Ørjan Myrland"
date: "17.09.2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
require(tidyverse)
```


```{r, include=FALSE}
eqnr <- read_csv("https://www.netfonds.no/quotes/paperhistory.php?paper=EQNR.OSE&csv_format=csv", 
     col_types = cols(quote_date = col_date(format = "%Y%m%d")))


nhy <- read_csv("https://www.netfonds.no/quotes/paperhistory.php?paper=NHY.OSE&csv_format=csv", 
     col_types = cols(quote_date = col_date(format = "%Y%m%d")))


merged <- merge(eqnr, nhy, by = "quote_date")

tail(nhy)
tail(eqnr)

```

# NORSK HYDRO & EQUINOR stock pricing 
## May 2001 -> Present 
```{r}
p <- ggplot() + 
  geom_line(data = merged, aes(x = quote_date, y = close.x) , color="red") +
  geom_line(data = merged, aes(x = quote_date, y = close.y) , color="#000000") + xlab("date") + ylab("price") 

p
```

Red = EQUINOR

BLACK = NORSK HYDRO
```{r, include=FALSE}
#f <- ggplot(merged, aes(x = quote_date, y = c(close.x, close.y))) + 
  #geom_line(aes(color = c(close.x, close.y))) +
  #scale_color_manual(values = c("red", "#000000")) +
  #scale_fill_manual(values = c("red", "#000000")) +
  #theme_minimal()
#f
```

## January 4th 2010 -> Present 

```{r}
# Use January 4, 2010 as the starting point of the plot.
# Set axis limits c(min, max)
min <- as.Date("2010-01-04")
max <- NA
p + scale_x_date(limits = c(min, max))
```

Red = EQUINOR

BLACK = NORSK HYDRO
